data:
  build: data
  container_name: postgresql_data
  volumes:
    - /var/lib/postgresql

server:
  build: server
  container_name: postgresql_server
  environment:
    - DEBIAN_FRONTEND=noninteractive
    - TERM=linux
  log_driver: syslog
  log_opt:
    address: "udp://127.0.0.1:514"
  ports:
    - "0.0.0.0:5432:5432/tcp"
  restart: always
  volumes_from:
    - data
